[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons-custom/itad_core,/mnt/extra-addons-odoo18/oca/field-service
data_dir = /var/lib/odoo
admin_passwd = admin

db_host = db18
db_port = 5432
db_user = odoo
db_password = odoo
