"""init sqlalchemy

Revision ID: 0001
Revises:
Create Date: 2023-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bol',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bol_number', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),  # Changed from enum
    sa.Column('customer_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('requirement_profile_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),  # Changed from enum
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bol_number')
    )
    op.create_table('domain_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_id_map',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('odoo_customer_id', sa.String(), nullable=True),
    sa.Column('odoo_location_id', sa.String(), nullable=True),
    sa.Column('odoo_work_order_id', sa.String(), nullable=True),
    sa.Column('odoo_day_route_id', sa.String(), nullable=True),
    sa.Column('routific_job_id', sa.String(), nullable=True),
    sa.Column('routific_vehicle_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('itad_entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_external_odoo_customer', 'external_id_map', ['odoo_customer_id'], unique=False)
    op.create_index('idx_external_odoo_day_route', 'external_id_map', ['odoo_day_route_id'], unique=False)
    op.create_index('idx_external_odoo_work_order', 'external_id_map', ['odoo_work_order_id'], unique=False)
    op.create_index('idx_external_routific_job', 'external_id_map', ['routific_job_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'route', 'method', name='uq_idempotency_key_route_method')
    )
    op.create_table('receiving_weight_record_v3',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bol_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('container_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('gross_weight', sa.Numeric(), nullable=False),
    sa.Column('tare_weight', sa.Numeric(), nullable=False),
    sa.Column('net_weight', sa.Numeric(), nullable=False),
    sa.Column('scale_id', sa.String(), nullable=False),
    sa.Column('hazard_class', sa.String(), nullable=True),
    sa.Column('un_number', sa.String(), nullable=True),
    sa.Column('ddr_status', sa.Boolean(), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=False),
    sa.Column('receiver_employee_id', sa.String(), nullable=True),
    sa.Column('receiver_signature_ref', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('voided_record_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bol_id'], ['bol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receiving_weight_record_v3')
    op.drop_table('idempotency_keys')
    op.drop_index('idx_external_routific_job', table_name='external_id_map')
    op.drop_index('idx_external_odoo_work_order', table_name='external_id_map')
    op.drop_index('idx_external_odoo_day_route', table_name='external_id_map')
    op.drop_index('idx_external_odoo_customer', table_name='external_id_map')
    op.drop_table('external_id_map')
    op.drop_table('domain_events')
    op.drop_table('bol')
    # ### end Alembic commands ###
