name: odoo-smoke

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  install-upgrade-smoke:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U odoo -d postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # (Опционально) Покажем структуру, чтобы проще дебажить пути
      - name: List repo
        run: |
          ls -la
          ls -la addons || true
          ls -la addons/common || true

      - name: Debug container odoo.conf
        run: |
          docker run --rm odoo:18.0 bash -lc 'ls -la /etc/odoo && echo "----" && (cat /etc/odoo/odoo.conf || true)'

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            nc -z 127.0.0.1 5432 && echo "Postgres is up" && exit 0
            echo "waiting for postgres..."
            sleep 1
          done
          echo "Postgres did not start in time" && exit 1

      - name: Install smoke (-i itad_core)
        run: |
          set -euxo pipefail
            test -f addons/common/itad_core/__manifest__.py
            test -f addons/odoo18/oca/field-service/fieldservice/__manifest__.py

            docker run --rm --network "${{ job.services.postgres.network }}" \
              -e HOST=postgres -e PORT=5432 -e USER=odoo -e PASSWORD=odoo \
              -v "${{ github.workspace }}:/mnt/extra-addons" \
              odoo:18.0 \
              odoo -c /dev/null \
              --db_host=postgres --db_port=5432 --db_user=odoo --db_password=odoo \
              -d itad_ci \
              --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/addons/common,/mnt/extra-addons/addons/odoo18/oca/field-service \
              -i itad_core \
              --stop-after-init



      - name: Upgrade smoke (-u itad_core)
        run: |
          set -euxo pipefail
          docker run --rm --network "${{ job.services.postgres.network }}" \
            -e HOST=postgres -e PORT=5432 -e USER=odoo -e PASSWORD=odoo \
            -v "${{ github.workspace }}:/mnt/extra-addons" \
            odoo:18.0 \
            odoo -c /dev/null \
                --db_host=postgres --db_port=5432 --db_user=odoo --db_password=odoo \
                -d itad_ci \
                --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/addons/common,/mnt/extra-addons/addons/odoo18/oca/field-service \
                -u itad_core \
                --stop-after-init



